[build]
builder = "DOCKERFILE"
buildCommand = "docker build --progress=plain ."
dockerfilePath = "Dockerfile"
buildEnvironment = "V2"
watchPatterns = ["requirements.txt", "Dockerfile"]


[deploy]
runtime = "V2"
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10